#
#    Copyright ${license.git.copyrightYears} the original author or authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

# extension of the tomcat:9.0 image
FROM tomcat:9.0
# arguments
ARG WAR_FILE=target/frontend.war
# copying war file to usr path
COPY ${WAR_FILE} /usr/local/tomcat/webapps/
EXPOSE 8080